version: '3.5'

networks:
  main:
    name: itu-minitwit-network

services:
  minitwit-database:
    image: postgres:16-alpine
    container_name: psql
    networks:
      - main
    environment:
      POSTGRES_USER: minitwit
      POSTGRES_DB: minitwit_test
      POSTGRES_PASSWORD: '1234'
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  minitwit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minitwit
    depends_on:
      minitwit-database:
        condition: service_healthy
    environment:
      - PORT=5000
      - APP_ENV=test
      - DATABASE_URL=postgresql://minitwit:1234@minitwit-database:5432/minitwit
    networks:
      - main
    ports:
        - '5000:5000'
    command:
      - /bin/bash
      - -c
      - |
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec ruby myapp.rb
