version: '3.5'

networks:
  main:
    name: itu-minitwit-network

services:
  minitwit:
    image: ${DOCKER_USERNAME}/minitwit
    container_name: minitwit
    environment:
      - DATABASE_PATH=./db/minitwit_dev.db
      - PORT=5000
    networks:
      - main
    ports:
        - '5000:5000'
    command:
      - /bin/bash
      - -c
      - |
        ./control.sh init
        bundle exec rake db:migrate
        bundle exec ruby myapp.rb
