FROM python:3.7-alpine

RUN mkdir /minitwit-tests

COPY refactored_minitwit_tests.py /minitwit-tests/

WORKDIR /minitwit-tests

RUN pip install pytest==5.3.5

EXPOSE 5000

ENTRYPOINT ["pytest", "-s", "refactored_minitwit_tests.py"]