FROM python:3.7-alpine

RUN mkdir /minitwit-api-tests

COPY ./simapi/ /minitwit-api-tests/
COPY requirements.txt /minitwit-api-tests/

WORKDIR /minitwit-api-tests

RUN pip install -r requirements.txt

RUN chmod +x /entrypoint.sh

# Set the entrypoint to the script
ENTRYPOINT ["/entrypoint.sh"]