FROM python:3.7-alpine

RUN mkdir /minitwit-api-tests

COPY ./simapi/ /minitwit-api-tests/
COPY requirements.txt /minitwit-api-tests/

WORKDIR /minitwit-api-tests

RUN pip install -r requirements.txt

EXPOSE 5001

ENTRYPOINT pytest -s minitwit_sim_api_test.py && python ./minitwit_simulator.py "http://minitwit-api:5001" true "./minitwit_scenario.csv" > ./simulator_output.txt && pytest ./minitwit_simulator_test.py