version: "3.3"

networks:
  main:

services:

  minitwitimage:
    image: aguldborg/minitwit
    command: bundle exec ruby myapp.rb
    container_name: interface
    environment:
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL} # Gets set by deploy.sh called from continous-deployment
    networks:
      - main
    ports:
      - "5000:5000"

  minitwitsimapiimage:
    image: aguldborg/minitwit
    command: bundle exec ruby simapi/sim_api.rb
    container_name: simapi
    environment:
      - PORT=5001
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - main
    expose:
      - "5001"
    ports:
      - "5001:5001"
