version: "3.3"

networks:
  main:

services:
  minitwitimage:
    image: aguldborg/minitwit:${MINITWIT_VERSION}
    command:
      - /bin/bash
      - -c
      - |
        bundle exec rake db:migrate
        bundle exec ruby myapp.rb
    container_name: interface
    environment:
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL} # Gets set by deploy.sh called from continous-deployment
      - NR_LICENSE_KEY=${NR_LICENSE_KEY}
    networks:
      - main
    ports:
      - "5000:5000"

  minitwitsimapiimage:
    image: aguldborg/minitwit:${MINITWIT_VERSION}
    command:
      - /bin/bash
      - -c
      - |
        bundle exec rake db:migrate
        bundle exec ruby simapi/sim_api.rb
    container_name: simapi
    environment:
      - PORT=5001
      - DATABASE_URL=${DATABASE_URL}
      - NR_LICENSE_KEY=${NR_LICENSE_KEY}
    networks:
      - main
    expose:
      - "5001"
    ports:
      - "5001:5001"
