---
name: Automatic Release

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
  
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.CI_TOKEN }}

      - name: Create release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v.${{ github.sha }}
          release_name: Release ${{ github.sha }}