---
name: Automatic Testing

on:
  # allow manual triggers for now too
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push minitwit
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwit:webbuildcache,mode=max

      - name: Build and push minitwit-api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./simapi/Dockerfile-api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwit-api:${{ github.sha }}

      - name: Run minitwit
        run: |
          docker compose -f docker-compose-tests.yaml build
          yes 2>/dev/null | docker compose -f docker-compose-tests.yaml up --abort-on-container-exit --exit-code-from test-runner
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MINITWIT_VERSION: ${{ github.sha }}

      - name: Run e2e minitwit
        run: |
          docker compose -f docker-compose-e2e-test.yaml build
          yes 2>/dev/null | docker compose -f docker-compose-e2e-test.yaml up --abort-on-container-exit --exit-code-from e2e-test-runner
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MINITWIT_VERSION: ${{ github.sha }}

      - name: Upload e2e report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Run minitwit api
        run: |
          docker compose -f docker-compose-api-test.yaml build
          yes 2>/dev/null | docker compose -f docker-compose-api-test.yaml up --abort-on-container-exit --exit-code-from api-test-runner
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MINITWIT_VERSION: ${{ github.sha }}
